name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.sha }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/multi-region-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/multi-region-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Ovaj posao čeka da se build uspešno završi
    steps:
    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Povezan na AWS server. Pokrećem deploy..."
          
          # Čekamo par sekundi za svaki slučaj da se Docker instalacija završi ako je server tek podignut
          sleep 10
          
          # Zaustavi i obriši stari kontejner ako postoji
          sudo docker stop backend-app || true
          sudo docker rm backend-app || true
          
          # Povuci najnoviju sliku sa DockerHub-a
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/multi-region-backend:latest
          
          # Pokreni novi kontejner na portu 8000
          sudo docker run -d \
            --name backend-app \
            -p 8000:8000 \
            --restart always \
            ${{ secrets.DOCKERHUB_USERNAME }}/multi-region-backend:latest
          
          echo "Deploy je uspešno završen!"
